export interface CodeSnippet {
  title: string;
  language: string;
  lines: string[];
  vulnLine: number; // 0-based
  vulnType: string;
  fix: string;
  d: number;
  glossary: string[];
}

export const VULN_TYPES = [
  'SQL Injection',
  'NoSQL Injection',
  'XSS (Cross-Site Scripting)',
  'Credenziali hardcoded',
  'Path Traversal',
  'IDOR / Autorizzazione mancante',
  'Command Injection',
  'Server-Side Template Injection',
  'Hash debole per password',
  'Uso di eval()',
  'Verifica firma/autenticazione mancante',
  'Open Redirect',
  'Confronto insicuro / logica errata',
  'Informazioni sensibili nei log',
  'Deserializzazione insicura',
  'Random non crittografico',
  'Permessi troppo ampi',
  'CSRF mancante',
];

export const CODE_SNIPPETS: CodeSnippet[] = [
  {
    title: 'Login pizzeria',
    language: 'php',
    d: 1,
    lines: [
      '<?php',
      '$user = $_POST["user"];',
      '$pass = $_POST["pass"];',
      '$q = "SELECT * FROM utenti WHERE user=\'$user\' AND pass=\'$pass\'";',
      '$res = mysqli_query($db, $q);',
      'if (mysqli_num_rows($res) > 0) { login(); }',
    ],
    vulnLine: 3,
    vulnType: 'SQL Injection',
    fix: 'La query concatena input non validato: \' OR \'1\'=\'1 bypassa il login. Usa prepared statements: $stmt = $db->prepare("SELECT * FROM utenti WHERE user=?"); poi verifica la password con password_verify() contro l\'hash (mai confrontarla in chiaro nella query).',
    glossary: ['sqli', 'prepared'],
  },
  {
    title: 'Chiave API nel codice',
    language: 'javascript',
    d: 1,
    lines: [
      'const express = require("express");',
      'const app = express();',
      'const API_KEY = "sk_live_51H8xQ2eZ9vB3mN7pL4kJ";',
      'app.get("/pay", (req, res) => {',
      '  stripe.charge(req.query.amount, API_KEY);',
      '});',
    ],
    vulnLine: 2,
    vulnType: 'Credenziali hardcoded',
    fix: 'Leggi la chiave da variabile d\'ambiente: const API_KEY = process.env.STRIPE_KEY; e non committare mai i segreti.',
    glossary: ['secrets'],
  },
  {
    title: 'Bacheca commenti',
    language: 'javascript',
    d: 1,
    lines: [
      'function mostraCommento(c) {',
      '  const div = document.createElement("div");',
      '  div.innerHTML = "<b>" + c.autore + "</b>: " + c.testo;',
      '  document.getElementById("bacheca").appendChild(div);',
      '}',
    ],
    vulnLine: 2,
    vulnType: 'XSS (Cross-Site Scripting)',
    fix: 'Usa textContent invece di innerHTML, oppure fai escaping di autore e testo prima di inserirli.',
    glossary: ['xss', 'escaping'],
  },
  {
    title: 'Download documenti',
    language: 'python',
    d: 2,
    lines: [
      '@app.route("/download")',
      'def download():',
      '    nome = request.args.get("file")',
      '    percorso = "/var/www/docs/" + nome',
      '    return send_file(percorso)',
    ],
    vulnLine: 3,
    vulnType: 'Path Traversal',
    fix: 'Valida il nome (niente "/" o ".."), usa os.path.basename() e verifica che il percorso finale sia dentro /var/www/docs.',
    glossary: ['traversal'],
  },
  {
    title: 'Ping dal pannello admin',
    language: 'python',
    d: 2,
    lines: [
      'import os',
      '@app.route("/ping")',
      'def ping():',
      '    host = request.args.get("host")',
      '    out = os.system("ping -c 1 " + host)',
      '    return str(out)',
    ],
    vulnLine: 4,
    vulnType: 'Command Injection',
    fix: 'Non concatenare input in comandi shell. Usa subprocess.run(["ping","-c","1",host]) dopo aver validato host con una regex.',
    glossary: ['cmdi'],
  },
  {
    title: 'Registrazione utente',
    language: 'python',
    d: 2,
    lines: [
      'import hashlib',
      'def registra(user, pw):',
      '    h = hashlib.md5(pw.encode()).hexdigest()',
      '    db.insert({"user": user, "hash": h})',
    ],
    vulnLine: 2,
    vulnType: 'Hash debole per password',
    fix: 'Usa bcrypt/argon2 con salt: bcrypt.hashpw(pw.encode(), bcrypt.gensalt()). MD5 si cracka in secondi.',
    glossary: ['hash', 'salt'],
  },
  {
    title: 'Calcolatrice web',
    language: 'javascript',
    d: 2,
    lines: [
      'app.post("/calc", (req, res) => {',
      '  const expr = req.body.expr;',
      '  const risultato = eval(expr);',
      '  res.json({ risultato });',
      '});',
    ],
    vulnLine: 2,
    vulnType: 'Uso di eval()',
    fix: 'Mai eval su input utente. Usa un parser matematico sicuro (es. mathjs) o una whitelist di caratteri.',
    glossary: ['eval'],
  },
  {
    title: 'Dettaglio ordine',
    language: 'javascript',
    d: 2,
    lines: [
      'app.get("/ordine/:id", auth, async (req, res) => {',
      '  const ordine = await Ordine.findById(req.params.id);',
      '  res.json(ordine);',
      '});',
    ],
    vulnLine: 1,
    vulnType: 'IDOR / Autorizzazione mancante',
    fix: 'Verifica che l\'ordine appartenga all\'utente loggato: Ordine.findOne({ _id: req.params.id, userId: req.user.id }).',
    glossary: ['idor'],
  },
  {
    title: 'Log del login',
    language: 'java',
    d: 3,
    lines: [
      'public boolean login(String user, String pass) {',
      '    logger.info("Login: " + user + " / " + pass);',
      '    User u = repo.find(user);',
      '    return u != null && u.checkPassword(pass);',
      '}',
    ],
    vulnLine: 1,
    vulnType: 'Informazioni sensibili nei log',
    fix: 'Mai loggare password o token. logger.info("Login tentativo: " + user) è sufficiente.',
    glossary: ['logs'],
  },
  {
    title: 'Reset password',
    language: 'javascript',
    d: 3,
    lines: [
      'function generaToken() {',
      '  return Math.floor(Math.random() * 1000000).toString();',
      '}',
      'app.post("/reset", (req, res) => {',
      '  const token = generaToken();',
      '  inviaEmail(req.body.email, token);',
      '});',
    ],
    vulnLine: 1,
    vulnType: 'Random non crittografico',
    fix: 'Math.random() è prevedibile e 6 cifre sono poche. Usa crypto.randomBytes(32).toString("hex").',
    glossary: ['csprng'],
  },
  {
    title: 'Confronto token',
    language: 'python',
    d: 3,
    lines: [
      'def verifica(token_ricevuto):',
      '    atteso = get_token_from_db()',
      '    if token_ricevuto == atteso:',
      '        return True',
      '    return False',
    ],
    vulnLine: 2,
    vulnType: 'Confronto insicuro / logica errata',
    fix: 'Il confronto == si ferma al primo byte diverso: timing attack. Usa hmac.compare_digest(token_ricevuto, atteso).',
    glossary: ['timing'],
  },
  {
    title: 'Upload avatar',
    language: 'php',
    d: 3,
    lines: [
      '$nome = $_FILES["avatar"]["name"];',
      '$dest = "uploads/" . $nome;',
      'move_uploaded_file($_FILES["avatar"]["tmp_name"], $dest);',
      'echo "Caricato in $dest";',
    ],
    vulnLine: 1,
    vulnType: 'Path Traversal',
    fix: 'Non usare il nome originale: genera un nome casuale, valida l\'estensione (whitelist) e il tipo MIME reale.',
    glossary: ['traversal', 'upload'],
  },
  {
    title: 'Ricerca prodotti',
    language: 'javascript',
    d: 3,
    lines: [
      'app.get("/cerca", async (req, res) => {',
      '  const q = req.query.q;',
      '  const rows = await db.query(`SELECT * FROM prodotti WHERE nome LIKE \'%${q}%\'`);',
      '  res.json(rows);',
      '});',
    ],
    vulnLine: 2,
    vulnType: 'SQL Injection',
    fix: 'db.query("SELECT * FROM prodotti WHERE nome LIKE ?", [`%${q}%`]) — i parametri non vengono mai interpretati come SQL.',
    glossary: ['sqli', 'prepared'],
  },
  {
    title: 'Cambio email',
    language: 'javascript',
    d: 3,
    lines: [
      'app.post("/cambia-email", auth, (req, res) => {',
      '  req.user.email = req.body.email;',
      '  req.user.save();',
      '  res.send("ok");',
      '});',
    ],
    vulnLine: 0,
    vulnType: 'CSRF mancante',
    fix: 'Un sito malevolo può inviare questo POST a nome dell\'utente loggato. Aggiungi un token anti-CSRF e cookie SameSite.',
    glossary: ['csrf'],
  },
  {
    title: 'Import configurazione',
    language: 'python',
    d: 4,
    lines: [
      'import pickle',
      '@app.route("/import", methods=["POST"])',
      'def importa():',
      '    dati = pickle.loads(request.data)',
      '    applica_config(dati)',
      '    return "ok"',
    ],
    vulnLine: 3,
    vulnType: 'Deserializzazione insicura',
    fix: 'pickle.loads su dati non fidati esegue codice arbitrario. Usa JSON con schema validato.',
    glossary: ['deser'],
  },
  {
    title: 'Backup notturno',
    language: 'bash',
    d: 4,
    lines: [
      '#!/bin/bash',
      'DATA=$(date +%F)',
      'tar czf /backup/db-$DATA.tgz /var/lib/mysql',
      'chmod 777 /backup/db-$DATA.tgz',
      'echo "Backup fatto"',
    ],
    vulnLine: 3,
    vulnType: 'Permessi troppo ampi',
    fix: 'Un backup del database leggibile da tutti gli utenti = tutti i dati esposti. Usa chmod 600 e proprietario dedicato.',
    glossary: ['perms'],
  },
  {
    title: 'Redirect dopo login',
    language: 'javascript',
    d: 4,
    lines: [
      'app.get("/login-ok", (req, res) => {',
      '  const next = req.query.next || "/";',
      '  res.redirect(next);',
      '});',
    ],
    vulnLine: 2,
    vulnType: 'Open Redirect',
    fix: 'Open redirect (CWE-601): ?next=https://sito-malevolo.it. Accetta solo percorsi relativi che iniziano con "/" (e non "//" né "/\\"). Meglio ancora: una allow-list di destinazioni.',
    glossary: ['openredirect'],
  },
  {
    title: 'Template email',
    language: 'python',
    d: 4,
    lines: [
      'from jinja2 import Template',
      'def email_benvenuto(nome):',
      '    t = Template("Ciao " + nome + ", benvenuto!")',
      '    return t.render()',
    ],
    vulnLine: 2,
    vulnType: 'Server-Side Template Injection',
    fix: 'Server-Side Template Injection (SSTI, CWE-1336): costruire il template concatenando input rende eseguibile nome="{{7*7}}", fino alla RCE. Non mettere mai dati utente nel testo del template: passali come variabili — Template("Ciao {{ nome }}").render(nome=nome).',
    glossary: ['ssti'],
  },
  {
    title: 'Verifica JWT',
    language: 'javascript',
    d: 5,
    lines: [
      'const jwt = require("jsonwebtoken");',
      'function verifica(token) {',
      '  const payload = jwt.decode(token);',
      '  if (payload.role === "admin") return true;',
      '  return false;',
      '}',
    ],
    vulnLine: 2,
    vulnType: 'Verifica firma/autenticazione mancante',
    fix: 'Verifica della firma mancante (CWE-347): jwt.decode legge il payload SENZA controllare la firma, quindi chiunque può forgiare un token con role:"admin". Usa jwt.verify(token, SECRET) specificando gli algoritmi ammessi.',
    glossary: ['jwt'],
  },
  {
    title: 'Esportazione report',
    language: 'java',
    d: 5,
    lines: [
      'public void esporta(String formato, String id) throws Exception {',
      '    String cmd = "/opt/report/gen.sh --id " + id + " --format " + formato;',
      '    Runtime.getRuntime().exec(cmd);',
      '}',
    ],
    vulnLine: 1,
    vulnType: 'Command Injection',
    fix: 'id="1; rm -rf /" esegue comandi. Usa ProcessBuilder con argomenti separati e valida id come numero.',
    glossary: ['cmdi'],
  },
  {
    title: 'Cookie di sessione',
    language: 'javascript',
    d: 5,
    lines: [
      'app.use(session({',
      '  secret: "keyboard cat",',
      '  cookie: { httpOnly: false, secure: false },',
      '}));',
    ],
    vulnLine: 2,
    vulnType: 'Permessi troppo ampi',
    fix: 'httpOnly:false permette a JS (XSS) di rubare il cookie; secure:false lo manda in chiaro. Usa httpOnly:true, secure:true, sameSite:"lax".',
    glossary: ['cookie'],
  },
  {
    title: 'Webhook pagamento',
    language: 'python',
    d: 5,
    lines: [
      '@app.route("/webhook", methods=["POST"])',
      'def webhook():',
      '    evento = request.json',
      '    if evento["type"] == "pagamento.ok":',
      '        segna_pagato(evento["ordine_id"])',
      '    return "ok"',
    ],
    vulnLine: 2,
    vulnType: 'Verifica firma/autenticazione mancante',
    fix: 'Nessuna verifica della firma del webhook: l\'endpoint è pubblico e chiunque può inviare "pagamento.ok" senza aver pagato. Verifica la firma HMAC dell\'header con il segreto condiviso dal provider (es. Stripe-Signature) usando un confronto a tempo costante.',
    glossary: ['webhook'],
  },
  {
    title: 'Ricerca utenti (NoSQL)',
    language: 'javascript',
    d: 4,
    lines: [
      'app.post("/login", async (req, res) => {',
      '  const u = await User.findOne({ user: req.body.user, pass: req.body.pass });',
      '  if (u) res.send("benvenuto");',
      '});',
    ],
    vulnLine: 1,
    vulnType: 'NoSQL Injection',
    fix: 'NoSQL injection: inviando pass={"$ne": null} l\'operatore $ne fa match con qualsiasi utente e bypassa il login. Valida che user e pass siano stringhe (non oggetti), e confronta la password con il suo hash (bcrypt/argon2), mai in chiaro.',
    glossary: ['nosqli'],
  },
];
