export interface PhishTemplate {
  d: number;
  fromName: string;
  fromAddr: string;
  subject: string;
  body: string;
  linkText?: string;
  linkHref?: string;
  attachment?: string;
  isPhishing: boolean;
  clue: string; // l'indizio corretto
  distractors: string[]; // altri "indizi" plausibili ma sbagliati
}

// clueOptions verranno costruite da clue + distractors + opzioni generiche
export const PHISH_TEMPLATES: PhishTemplate[] = [
  // ===== PHISHING FACILI =====
  {
    d: 1,
    fromName: 'Poste Italiane',
    fromAddr: 'servizio@poste-italliane-sicurezza.com',
    subject: 'URGENTE: il tuo conto sara bloccato tra 24 ore!!!',
    body: 'Gentile cliente, abbiamo rilevato attivita sospetta. Clicca subito per verificare i tuoi dati altrimenti il conto verra bloccato definitivamente.',
    linkText: 'Verifica ora il tuo account',
    linkHref: 'http://poste-verifica-conto.sicurezza-login.ru/auth',
    isPhishing: true,
    clue: 'Il dominio del link (.ru) e del mittente non sono quelli ufficiali di Poste',
    distractors: ['Le Poste non usano le email', 'Il messaggio è scritto in italiano'],
  },
  {
    d: 1,
    fromName: 'Amazon Prime',
    fromAddr: 'no-reply@amaz0n-rewards.net',
    subject: 'Hai vinto un iPhone 15! Reclama il premio',
    body: 'Congratulazioni! Sei stato selezionato tra i nostri clienti fedeli. Per ricevere il tuo iPhone 15 gratis, conferma il pagamento delle spese di spedizione (1€).',
    linkText: 'Reclama il tuo iPhone',
    linkHref: 'http://amaz0n-rewards.net/claim?id=9912',
    isPhishing: true,
    clue: 'Premio troppo bello per essere vero + dominio con "0" al posto di "o" (amaz0n)',
    distractors: ['Amazon non vende iPhone', 'Le spese di 1€ sono troppo alte'],
  },
  {
    d: 1,
    fromName: 'Prof.ssa Rossi',
    fromAddr: 'maria.rossi@liceoturing.edu.it',
    subject: 'Compiti per lunedì',
    body: 'Ragazzi, per lunedì leggete il capitolo 4 e fate gli esercizi 1-5. Ci vediamo in classe. Buono studio!',
    isPhishing: false,
    clue: 'Mittente coerente, nessun link sospetto, nessuna urgenza o richiesta di dati',
    distractors: ['Non c\'è la firma completa', 'La mail è troppo breve'],
  },
  {
    d: 1,
    fromName: 'Netflix',
    fromAddr: 'info@netflix-pagamenti-it.info',
    subject: 'Il tuo pagamento non è andato a buon fine',
    body: 'Abbiamo riscontrato un problema con il tuo metodo di pagamento. Aggiorna i dati della carta entro oggi per non perdere l\'abbonamento.',
    linkText: 'Aggiorna metodo di pagamento',
    linkHref: 'http://netflix-pagamenti-it.info/billing',
    isPhishing: true,
    clue: 'Dominio non ufficiale (netflix-pagamenti-it.info) e richiesta urgente dei dati della carta',
    distractors: ['Netflix non invia mai email', 'Il logo manca'],
  },

  // ===== PHISHING MEDI =====
  {
    d: 3,
    fromName: 'IT Support',
    fromAddr: 'it-support@shopfast-it.com',
    subject: 'Aggiornamento obbligatorio della password',
    body: 'A seguito di una policy di sicurezza, tutti i dipendenti devono reimpostare la password aziendale entro oggi. Accedi al portale e segui le istruzioni.',
    linkText: 'Portale reset password',
    linkHref: 'https://shopfast-it.com.account-security.co/reset',
    isPhishing: true,
    clue: 'Il dominio reale è "account-security.co", non "shopfast-it.com" (è solo un sottodominio ingannevole)',
    distractors: ['Usa HTTPS quindi è sicuro', 'L\'IT non manda mai email'],
  },
  {
    d: 3,
    fromName: 'Marta Bianchi (CTO)',
    fromAddr: 'marta.bianchi@shopfast.com',
    subject: 'Riunione team sicurezza - giovedì 15',
    body: 'Ciao, ci vediamo giovedì alle 15 in sala riunioni per discutere i risultati del pentest. Porta il report aggiornato. Grazie, Marta.',
    isPhishing: false,
    clue: 'Dominio aziendale corretto, richiesta coerente col contesto, nessun link o allegato sospetto',
    distractors: ['Non specifica la sala', 'Marta non scrive mai email'],
  },
  {
    d: 3,
    fromName: 'DHL Express',
    fromAddr: 'tracking@dhl-consegne.com',
    subject: 'Pacco in giacenza - azione richiesta',
    body: 'Il tuo pacco è fermo in dogana. Per completare la consegna è necessario pagare 2,99€ di spese doganali. Inserisci i dati della carta per sbloccare.',
    linkText: 'Paga e sblocca il pacco',
    linkHref: 'http://dhl-consegne.com/pay',
    attachment: undefined,
    isPhishing: true,
    clue: 'Richiesta di pagamento con carta su dominio non ufficiale per una cifra piccola (tecnica comune)',
    distractors: ['DHL non consegna pacchi', '2,99€ è una cifra troppo bassa per essere vera'],
  },
  {
    d: 3,
    fromName: 'Microsoft 365',
    fromAddr: 'account-security-noreply@accountprotection.microsoft.com',
    subject: 'Nuovo accesso dal tuo account',
    body: 'Abbiamo rilevato un nuovo accesso da Milano, Italia, su Windows. Se sei stato tu, ignora questo messaggio. Altrimenti proteggi il tuo account.',
    linkText: 'Rivedi attività',
    linkHref: 'https://account.microsoft.com/security',
    isPhishing: false,
    clue: 'Dominio ufficiale Microsoft, nessuna urgenza forzata, il link punta al sito reale microsoft.com',
    distractors: ['Segnala un accesso quindi è un attacco', 'Microsoft non monitora gli accessi'],
  },
  {
    d: 3,
    fromName: 'Ufficio Risorse Umane',
    fromAddr: 'hr@shopfast.com',
    subject: 'Busta paga - Novembre.pdf',
    body: 'In allegato trovi la busta paga del mese. Per visualizzarla abilita le macro e inserisci la password aziendale quando richiesto.',
    attachment: 'BustaPaga_Novembre.xlsm',
    isPhishing: true,
    clue: 'Allegato .xlsm che chiede di "abilitare le macro" + richiesta della password: classico malware',
    distractors: ['Le buste paga non sono in PDF', 'Novembre è già passato'],
  },

  // ===== PHISHING DIFFICILI =====
  {
    d: 4,
    fromName: 'Dott. Ferri',
    fromAddr: 'g.ferri@bancadigitale.com',
    subject: 'R: Report pentest Q4',
    body: 'Grazie per il report. Ho una domanda su una delle finding. Puoi richiamarmi al numero interno 4412 quando hai un momento? Grazie.',
    isPhishing: false,
    clue: 'Risposta coerente in un thread esistente, dominio corretto, nessun link/allegato, chiede solo una chiamata interna',
    distractors: ['Un interno a 4 cifre non esiste', 'I CISO non leggono i report'],
  },
  {
    d: 4,
    fromName: 'Dott. Ferri - BancaDigitale',
    fromAddr: 'g.ferri@banca-digitale.com',
    subject: 'R: Report pentest Q4 - urgente',
    body: 'Ottimo lavoro. Mi serve subito l\'accesso VPN di test che hai usato: inviami username e password a questo indirizzo, il mio account interno è in manutenzione. È urgente per il board di stasera.',
    isPhishing: true,
    clue: 'Dominio con trattino (banca-digitale.com ≠ bancadigitale.com) + richiede credenziali per email con urgenza',
    distractors: ['Il board non si riunisce di sera', 'Ferri ha già le credenziali'],
  },
  {
    d: 4,
    fromName: 'GitHub',
    fromAddr: 'noreply@github.com',
    subject: '[GitHub] A third-party OAuth application has been added',
    body: 'The OAuth application "CloudDeploy-CI" was recently authorized to access your account with repo and admin:org scopes. If this was you, no action is needed.',
    linkText: 'Review authorized applications',
    linkHref: 'https://github.com/settings/applications',
    isPhishing: false,
    clue: 'Dominio github.com autentico e link al vero pannello settings: è una notifica di sicurezza legittima',
    distractors: ['GitHub non invia notifiche OAuth', 'Gli scope admin:org sono inventati'],
  },
  {
    d: 4,
    fromName: 'Assistenza Clienti',
    fromAddr: 'support@paypaI.com',
    subject: 'Transazione non autorizzata di 459,90€',
    body: 'Abbiamo bloccato una transazione sospetta di 459,90€ verso un venditore in Cina. Se non la riconosci, annullala entro 12 ore effettuando il login.',
    linkText: 'Annulla la transazione',
    linkHref: 'https://www.paypaI.com/it/cancel',
    isPhishing: true,
    clue: 'Il dominio usa una "I" maiuscola al posto della "l" (paypaI ≠ paypal): omoglifo',
    distractors: ['PayPal non blocca le transazioni', '459,90€ è una cifra sospetta'],
  },
  {
    d: 5,
    fromName: 'Dott.ssa Conti',
    fromAddr: 'conti@medlife-hospital.com',
    subject: 'Referto paziente - consulto urgente',
    body: 'Collega, le inoltro il referto del paziente in allegato per un consulto. È urgente, il paziente è in attesa. La password del file è "medlife2024".',
    attachment: 'Referto_Paziente_4471.html',
    isPhishing: true,
    clue: 'Allegato .html (una pagina di login fasulla) mascherato da referto + password nel corpo per dare credibilità',
    distractors: ['I referti sono sempre in PDF', 'I medici non usano allegati'],
  },
  {
    d: 5,
    fromName: 'Security Team',
    fromAddr: 'security@nimbuscloud.eu',
    subject: 'Rotazione chiavi API programmata - 15/12',
    body: 'Come da calendario, le chiavi API del tuo progetto verranno ruotate il 15/12 alle 02:00 UTC. Trovi le nuove chiavi nella dashboard. Nessuna azione richiesta da parte tua.',
    linkText: 'Apri dashboard',
    linkHref: 'https://console.nimbuscloud.eu/keys',
    isPhishing: false,
    clue: 'Dominio corretto, processo programmato e atteso, "nessuna azione richiesta", link alla console reale',
    distractors: ['Le chiavi non si ruotano mai', '02:00 UTC è un orario strano'],
  },
  {
    d: 5,
    fromName: 'Sam (VP Security)',
    fromAddr: 'sam@nebula-corp.com',
    subject: 'Quick favor - gift cards per il team',
    body: 'Sono in riunione e non posso chiamare. Mi serve un favore veloce: compra 5 gift card Amazon da 100€ per il riconoscimento del team e inviami i codici. Ti rimborso oggi. Grazie!',
    isPhishing: true,
    clue: 'Classica truffa BEC "gift card": urgenza, impossibilità di chiamare, richiesta di codici gift card',
    distractors: ['Le gift card Amazon non arrivano a 100€', 'Sam non beve caffè'],
  },
  {
    d: 5,
    fromName: 'LinkedIn',
    fromAddr: 'security-noreply@linkedin.com',
    subject: 'Please verify your email address',
    body: 'We noticed a sign-in attempt that required additional verification. Enter this code in the app to continue: 402 815. This code expires in 10 minutes.',
    isPhishing: false,
    clue: 'Codice OTP da inserire NELL\'APP (non un link da cliccare), dominio ufficiale: notifica 2FA legittima',
    distractors: ['LinkedIn non usa codici OTP', 'Il codice a 6 cifre è troppo corto'],
  },
];

export const GENERIC_CLUES = [
  'Non c\'è il logo aziendale',
  'L\'email è troppo breve',
  'È scritta in inglese',
  'Manca la firma del mittente',
  'Arriva fuori orario di ufficio',
  'Contiene allegati (sempre pericolosi)',
];
